### ISSUE TITLE
Singularity Hub Builds

### ISSUE THREAD

**Issue by vsoch** [kma/singularity-jupyter#1]
Hey @kma! I'm the developer of Singularity Hub - it looks like your container associated with this repo is having trouble building. Have you tested this locally and can confirm that it works? Does it require the new (2.3) version of Singularity? I'd like to offer to help to get the build working. Let me know!

**Comment by vsoch** [comment]
Reference to the build here: https://singularity-hub.org/collections/144/ The builder has been running for two days and is still in the Active Queue, and will be cancelled soon. This also appears to have happened for your first attempt at this build (the one that is cancelled)

**Comment by kma** [comment]
Hi Vanessa,
Locally it works, I used the development version. The Singularity file try to install Jupyter notebook. 
I do not understand why it does not work.
Best.

**Comment by kma** [comment]
Hi @vsoch I removed this line: `rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*` from Singularity file and the build is completed. 
Thank you.

**Comment by vsoch** [comment]
perfecto! Thanks for checking this out. It makes perfect sense, actually - we build into a folder to estimate size, so removing tmp would have actually removed that image and the log. Hopefully in the next round we will have better ways to estimate the size of the build! Thanks again, closing issue.
